# == System Packages ==
apt:
  common:
    - iperf
    #- python2.7
    - python-setuptools
    - build-essential
    - cmake
    - cppcheck
    - gdb
    - git
    - lsb-release
    - software-properties-common
    - sudo
    - vim
    - nano
    - emacs
    - wget
    - curl
    - less
    - net-tools
    - tmux
    - byobu
    - iputils-ping
    - locales
    - xvfb
    - tzdata
    - debian-archive-keyring
    - apt-transport-https
    - git-lfs
    - traceroute
    - zsh
    - lm-sensors
    - tmuxp
    # azure vpn
    - strongswan
    - strongswan-pki
    - libstrongswan-extra-plugins
    - network-manager-strongswan
    # azure rdp
    - rdesktop
    # azure cli
    - ca-certificates
    - curl
    - gnupg
    - bash-completion
    - libssl-dev
    - libffi-dev
    - htop
    - iftop
    - sshpass
    - python3-dev
    - python3-pip
    - openssh-server
    - jq
    - inotify-tools
    - sshfs
    - ansible
    - socat
    - ethtool
  arm:
    #- backports.ssl_match_hostname
    - libboost-all-dev
    - libeigen3-dev
    - assimp-utils
    - libcgal-dev
    - libcgal-qt5-dev
    - libproj-dev
    - libnlopt-dev
    #- wstool
    # - python-catkin-tools
    - libglfw3-dev
    - libblosc-dev
    - libopenexr-dev
    - liblog4cplus-dev
    - libsuitesparse-dev
    - libsdl1.2-dev
    - libncurses5-dev
    - libpcap-dev
    - graphviz
    - doxygen
    - sharutils

  gstreamer:
    - libgstreamer1.0-0
    # - gstreamer1.0-dev
    - gstreamer1.0-tools
    - gstreamer1.0-doc
    - gstreamer1.0-libav

  ubuntu_1804:
    - python-requests
    - freerdp-x11

  rdp_packages:
    - xfce4
    - xrdp

  gnome_vanilla_packages:
    - gdm3
    - gnome-session

  gnome_prerequisite_packages:
    - tasksel

  gnome_desktop_packages:
    - ubuntu-desktop
    - xserver-xorg-video-dummy

  # ROS packages for base melodic install
  ros_melodic:
    pre:
      - python
      - python-rosdep
      - python-rosinstall-generator
      - python-wstool
      - python-rosinstall
      - python-catkin-tools
    extra:
      - ros-melodic-cmake-modules
      - ros-melodic-rqt-gui-cpp
      - ros-melodic-rviz
      - ros-melodic-gazebo-*
      - ros-melodic-rqt-gui
      - ros-melodic-rqt-gui-cpp
      - ros-melodic-rqt-gui-py
      - ros-melodic-catch-ros

  ros_noetic:
    pre:
      - python
      - python3-rosdep
      - python3-rosinstall
      - python3-rosinstall-generator
      - python3-wstool
      - build-essential
      - python3-catkin-pkg
      - python3-catkin-tools
    extra:
      - ros-noetic-cmake-modules
      - ros-noetic-rqt-gui-cpp
      - ros-noetic-rviz
      - ros-noetic-gazebo-*
      - ros-noetic-rqt-gui
      - ros-noetic-rqt-gui-cpp
      - ros-noetic-rqt-gui-py
      - ros-noetic-catch-ros

  ros_humble:
    pre:
      - python3-colcon-common-extensions
      #- python3-catkin-tools
    extra:
      - ros-dev-tools
      - python3-rosdep 
      - python3-rosinstall
      - python3-rosinstall-generator
      - python3-wstool
      - build-essential
pip3:
  common:
    - wheel
    - setuptools==69.2.0
    - shyaml
    - docker==6.1.3 
    - requests==2.31.0
